const FETCH_LIST_CHATBOXS = 'chats/FETCH_LIST_CHATBOXS';
const UPDATE_UNREAD_CHATS = 'chats/UPDATE_UNREAD_CHATS';
const DELETE_CHAT_GROUP = 'chats/DELETE_CHAT_GROUP';
const UPDATE_CHAT_GROUP = 'chats/UPDATE_CHAT_GROUP';
const GET_INFO_ROOM_CHAT = 'chats/GET_INFO_ROOM_CHAT';
const ADD_NEW_CHAT_BOX = 'chats/ADD_NEW_CHAT_BOX';
const UPDATE_NEW_MESSAGES_BOX = 'chats/UPDATE_NEW_MESSAGES_BOX';
const UPDATE_IS_JOIN = 'chats/UPDATE_IS_JOIN';
export {
  FETCH_LIST_CHATBOXS,
  UPDATE_UNREAD_CHATS,
  DELETE_CHAT_GROUP,
  UPDATE_CHAT_GROUP,
  GET_INFO_ROOM_CHAT,
  ADD_NEW_CHAT_BOX,
  UPDATE_NEW_MESSAGES_BOX,
  UPDATE_IS_JOIN,
};
