const GET_DIMENSIONS_DEVICE = 'dataCache/GET_DIMENSIONS_DEVICE';
const LOADING_START = 'dataCache/LOADING_START';
const LOADING_FINISH = 'dataCache/LOADING_FINISH';
const SET_SCREEN_NAVIGATION = 'dataCache/SET_SCREEN_NAVIGATION';
const FETCH_NETWORK_STATUS = 'dataCache/FETCH_NETWORK_STATUS';
const IS_LOAD_CONSTRUCTION = 'dataCache/IS_LOAD_CONSTRUCTION';
const IS_LONGPRESS_IMAGE = 'dataCache/IS_LONGPRESS_IMAGE';
const LIST_IMAGE_DELELE = 'dataCache/LIST_IMAGE_DELELE'
export {
  GET_DIMENSIONS_DEVICE,
  LOADING_START,
  LOADING_FINISH,
  SET_SCREEN_NAVIGATION,
  FETCH_NETWORK_STATUS,
  IS_LOAD_CONSTRUCTION,
  IS_LONGPRESS_IMAGE,
  LIST_IMAGE_DELELE
};
