const CREATE_ROOM = 'groupChat/CREATE_ROOM';
const CLOSE_SOCKET = 'groupChat/CLOSE_SOCKET';
const SET_VAL_IS_CLOSE_SOCKET = 'groupChat/SET_VAL_IS_CLOSE_SOCKET';
const SET_TIMER_INTERVAL = 'groupChat/SET_TIMER_INTERVAL';
const CLEAR_TIMER_INVERVAL = 'groupChat/CLEAR_TIMER_INVERVAL';
export {
  CREATE_ROOM,
  CLOSE_SOCKET,
  SET_VAL_IS_CLOSE_SOCKET,
  SET_TIMER_INTERVAL,
  CLEAR_TIMER_INVERVAL,
};
