const FETCH_DATA_LIST_IMAGE_CURRENT_DAY =
  'image/FETCH_DATA_LIST_IMAGE_CURRENT_DAY';
const FETCH_DATA_LIST_IMAGE_DAY_BEFORE =
  'image/FETCH_DATA_LIST_IMAGE_DAY_BEFORE';
const GET_LIST_DAY_BEFORE_PAGINATION = 'image/GET_LIST_DAY_BEFORE_PAGINATION';

const CAPTURE_IMAGE='image/CAPTURE_IMAGE';
export {
  FETCH_DATA_LIST_IMAGE_CURRENT_DAY,
  FETCH_DATA_LIST_IMAGE_DAY_BEFORE,
  GET_LIST_DAY_BEFORE_PAGINATION,
  CAPTURE_IMAGE
};
