const CREATE_ROOM = 'individualChat/CREATE_ROOM';
const CLOSE_SOCKET = 'individualChat/CLOSE_SOCKET';
const SET_VAL_IS_CLOSE_SOCKET = 'individualChat/SET_VAL_IS_CLOSE_SOCKET';
const SET_TIMER_INTERVAL = 'individualChat/SET_TIMER_INTERVAL';
const CLEAR_TIMER_INVERVAL = 'individualChat/CLEAR_TIMER_INVERVAL';
export {
  CREATE_ROOM,
  CLOSE_SOCKET,
  SET_VAL_IS_CLOSE_SOCKET,
  SET_TIMER_INTERVAL,
  CLEAR_TIMER_INVERVAL,
};
