const FETCH_DATA_ROOM_MESSAGE = 'messages/FETCH_DATA_ROOM_MESSAGE';

const ADD_MESSAGE_ROOM = 'messages/ADD_MESSAGE_ROOM';

const UPDATE_MESSAGE_ROOM  = 'messages/UPDATE_MESSAGE_ROOM';

const GET_MESSAGE_ROOM  = 'messages/GET_MESSAGE_ROOM';

export {FETCH_DATA_ROOM_MESSAGE,ADD_MESSAGE_ROOM,UPDATE_MESSAGE_ROOM,GET_MESSAGE_ROOM};
