const USER_INFO = 'user/USER_INFO';
const GET_ALBUM_PAGINATION = 'user/GET_ALBUM_PAGINATION';
const UPDATE_AVATAR_PROFILE = 'user/UPDATE_AVATAR_PROFILE';
export {USER_INFO, GET_ALBUM_PAGINATION, UPDATE_AVATAR_PROFILE};
